# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: | 
      sudo add-apt-repository -y ppa:duggan/bats
      sudo apt-get update
      sudo apt-get install -y bats
      npm install 
    command: node --inspect-brk dockerproxy.js setup
  # Test
  - command: cd test && bats test.bats


ports:
  - port: 9299
    onOpen: ignore