name: PR - Test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y expect
      - name: Test
        run: npm link && ./test/setup.exp
      - name: Test
        run: npm run test-ci
